// <auto-generated />
namespace Lab1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SimpleValidationV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SimpleValidationV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202104301358378_SimpleValidationV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
