//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AditionServices
    {
        public int Id { get; set; }
        public int Price { get; set; }
        public Nullable<int> Living_Id { get; set; }
        public Nullable<int> ServiceTypesId { get; set; }
        public System.DateTime DateOfService { get; set; }
        public Nullable<int> LivingsId { get; set; }
    
        public virtual Livings Livings { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
    }
}
