//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnectionEntities : DbContext
    {
        public DefaultConnectionEntities()
            : base("name=DefaultConnectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AditionServices> AditionServices { get; set; }
        public virtual DbSet<Apartments> Apartments { get; set; }
        public virtual DbSet<ApartmentTypes> ApartmentTypes { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Livings> Livings { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<ServiceTypes> ServiceTypes { get; set; }
    }
}
